export const globalConfig = {
  API_URL: process.env.NEXT_PUBLIC_APP_API,
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "",
  FACEBOOK_CLIENT_ID: process.env.NEXT_PUBLIC_FACEBOOK_APP_ID,
  UPLOADTHING_TOKEN: process.env.NEXT_PUBLIC_UPLOADTHING_TOKEN,
  DEEPGRAM_API_KEY: process.env.NEXT_PUBLIC_DEEPGRAM_API_KEY,
  AI_API_KEY: process.env.NEXT_PUBLIC_AI_API_KEY,
  GIPHY_API_KEY: process.env.NEXT_PUBLIC_GIPHY_API_KEY,
  APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,
};
